#!/usr/bin/env bash
#script that displays a list of currently running processes

echo "List of Currently Running Processes (with Hierarchy):"
echo "---------------------------------------------------"
echo "USER         PID  PPID  %CPU  %MEM    VSZ   RSS  TTY  STAT  START   TIME  COMMAND"

ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
