#!/usr/bin/env bash
#script that displays Best School 10 times, but for the 9th iteration, displays Best School the Hi on a new line

i=0
while [ $i -lt 10 ]
do
          echo "Best School"
          i=$(( i+1 ))
          if [ $i -eq 9 ]
	  then 
              echo "Hi"
       fi
done
