#!/usr/bin/env bash
#script that gives you information about school file

name=school
if [ -e $name ]; then
       echo "school file exists"
    else
          echo "school file does not exist"
         exist 1
fi
if [ ! -s $name ]; then

     echo "school file is empty" 

else 
       echo "school file is not empty"
fi

if [ -f $name ]; then

      echo "school is a regular file"
fi
